services:
  eventsweb:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: dev

    ports:
      - "3000:3000"

    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/app

    environment:
      - NODE_ENV=development
